/* ========================================
   NeuroClaw Agent Registry — Data
   ======================================== */

const AGENTS = [
  {
    id: "eedeb377-74d6-4702-aa98-544404efdf2f",
    name: "A.S.A.G.I",
    role: "NeuroClaw Code CLI Specialist",
    description: "Command-line interface specialist for the NeuroClaw ecosystem. Handles code operations, CLI tooling, and terminal-based workflows with precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#8b5cf6",
    image: "images/agents/a-s-a-g-i.png"
  },
  {
    id: "c001a6e9-89d1-438f-9be9-5658e0ab1328",
    name: "Akeno",
    role: "Academic Support & Homework Strategy",
    description: "Your dedicated academic companion. Provides homework help, study strategies, essay guidance, and tutoring across all subjects with patience and clarity.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Education",
    accent: "#0ea5e9",
    image: "images/agents/akeno.png"
  },
  {
    id: "c60026b0-4597-44e1-92f5-b2e287e4b59f",
    name: "Analyst",
    role: "Data Analysis & Structured Reporting",
    description: "Data analysis, comparisons, evaluations, and structured reporting specialist. Transforms raw data into actionable insights with clarity.",
    model: "gpt-5.1",
    status: "inactive",
    temporary: false,
    category: "Intelligence",
    accent: "#64748b",
    image: "images/agents/analyst.png"
  },
  {
    id: "6169b182-2795-4906-8f1b-f0a2a693d23d",
    name: "Angelina",
    role: "Docker, Containers & Infrastructure",
    description: "Containerization expert specializing in Docker, container orchestration, and infrastructure management. Keeps deployments running smoothly.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#10b981",
    image: "images/agents/angelina.png"
  },
  {
    id: "d8203660-535b-48a6-b4f0-279ed3218e93",
    name: "Asagi Aiba",
    role: "Electronics & Device Operations Specialist",
    description: "Electronics and device operations expert. Handles hardware interfacing, device configurations, and embedded systems with technical precision.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#06b6d4",
    image: "images/agents/asagi-aiba.png"
  },
  {
    id: "306faff2-e07d-47c3-a0c4-bf55ca9f9cef",
    name: "Asia",
    role: "UI/UX Designer",
    description: "Creative UI/UX designer crafting beautiful, intuitive interfaces. Specializes in user experience flows, visual design systems, and frontend aesthetics.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#ec4899",
    image: "images/agents/asia.png"
  },
  {
    id: "456250d0-4514-4a53-b5a4-3eb19c6f0c3d",
    name: "Asuna",
    role: "Family Systems & Parenting",
    description: "Compassionate guide for family dynamics, parenting strategies, and household management. Offers warm, practical advice for modern families.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f472b6",
    image: "images/agents/asuna.png"
  },
  {
    id: "885e5c37-c752-495c-902e-4d04a593ec54",
    name: "Batman",
    role: "Performance, Conditioning & Discipline",
    description: "Peak performance coach focused on physical conditioning, mental discipline, and building unbreakable habits. No excuses, just results.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f59e0b",
    image: "images/agents/batman.png"
  },
  {
    id: "95947325-bac9-4548-9b24-31ab481ba08e",
    name: "Cassandra Cain",
    role: "Recovery, Nutrition & Wellness",
    description: "Holistic wellness specialist covering nutrition, recovery protocols, injury prevention, and mindful health practices for sustainable wellbeing.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#84cc16",
    image: "images/agents/cassandra-cain.png"
  },
  {
    id: "50db7885-5f71-4755-9062-8e2da82b6ebc",
    name: "DINAH",
    role: "Technical Movement & Combat Mastery",
    description: "Technical movement and combat systems specialist. Analyzes martial arts, tactical movement, and physical combat mechanics with expert precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#ef4444",
    image: "images/agents/dinah.png"
  },
  {
    id: "378a8a0a-ddcb-432d-8b4f-eba0711c11fb",
    name: "Da Vinci",
    role: "AI Visual Architect",
    description: "Master visual artist leveraging AI image generation. Creates stunning, imaginative visuals and guides creative image-making workflows.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#a855f7",
    image: "images/agents/da-vinci.png"
  },
  {
    id: "07b3ccfe-bfd8-4c65-a494-3501890d2d4e",
    name: "F.R.I.D.A.Y",
    role: "Frontend Implementation",
    description: "Frontend engineering specialist turning designs into living code. Expert in React, Vue, CSS architecture, and modern web development.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#6366f1",
    image: "images/agents/f-r-i-d-a-y.png"
  },
  {
    id: "c8deb87e-6be3-4db8-9fbd-07a7d2db39d8",
    name: "Felicity",
    role: "I.T",
    description: "Information Technology specialist handling system administration, troubleshooting, networking, and general IT operations with efficiency.",
    model: "claude-opus-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#14b8a6",
    image: "images/agents/felicity.png"
  },
  {
    id: "3fe256ed-0c17-4320-8b05-2c0dad785c37",
    name: "Grayfia Lucifuge",
    role: "Treasury & Financial Intelligence Specialist",
    description: "Sophisticated financial intelligence analyst. Manages treasury operations, investment research, market analysis, and wealth strategy.",
    model: "gpt-5.5",
    status: "active",
    temporary: false,
    category: "Finance",
    accent: "#eab308",
    image: "images/agents/grayfia-lucifuge.png"
  },
  {
    id: "fcdd7bfe-3912-4905-9e4c-0339a73074f3",
    name: "Harley",
    role: "Mental Health, Emotional Support & Self-Awareness",
    description: "Empathetic mental health companion offering emotional support, self-awareness guidance, and therapeutic conversation in a safe space.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f43f5e",
    image: "images/agents/harley.png"
  },
  {
    id: "08a19e80-76f7-407c-a0a3-64707d3bccf2",
    name: "Honoka Mitsui",
    role: "Anime & Media Companion",
    description: "Enthusiastic anime and media companion. Discusses series, characters, tropes, and recommendations with genuine passion and knowledge.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#fb923c",
    image: "images/agents/honoka-mitsui.png"
  },
  {
    id: "4aba3dfb-f765-4f6b-ae01-a71e07a5a817",
    name: "Irina Shidou",
    role: "Financial Wellness & Personal Finance Assistant",
    description: "Personal finance coach helping with budgeting, savings strategies, debt management, and building healthy financial habits for everyday life.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Finance",
    accent: "#22c55e",
    image: "images/agents/irina-shidou.png"
  },
  {
    id: "9effc073-592c-485d-96b4-a432b31d4214",
    name: "Jarvis",
    role: "Coding Companion",
    description: "Reliable coding companion for software development. Assists with debugging, architecture decisions, code reviews, and learning new technologies.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#3b82f6",
    image: "images/agents/jarvis.png"
  },
  {
    id: "70155e82-66ef-4572-9ab5-032f81090509",
    name: "Jibril",
    role: "Semantic Memory & RAG Intelligence Specialist",
    description: "Memory architecture expert specializing in semantic search, RAG systems, vector databases, and knowledge retrieval infrastructure.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#8b5cf6",
    image: "images/agents/jibril.png"
  },
  {
    id: "09b58b3d-6375-4971-8aa6-caee857efbdf",
    name: "Joker",
    role: "Script, Content & Creative Writing Specialist",
    description: "Creative writing virtuoso crafting scripts, stories, content, and compelling narratives across all genres and formats with flair.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#a855f7",
    image: "images/agents/joker.png"
  },
  {
    id: "fefd7d62-7441-4a27-b96b-a2d29a00c231",
    name: "Kuroka",
    role: "Shadow Interaction & Unrestricted Conversation",
    description: "Unfiltered conversation partner for unrestricted dialogue. Engages openly on any topic without conventional boundaries or limitations.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#7c3aed",
    image: "images/agents/kuroka.png"
  },
  {
    id: "432e7ff0-9e6b-4019-b74c-6de4ec7a623b",
    name: "Kurumi",
    role: "Phone Flipping Specialist",
    description: "Mobile device commerce expert specializing in phone flipping, market valuation, sourcing strategies, and resale optimization.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#f97316",
    image: "images/agents/kurumi.png"
  },
  {
    id: "c9f5054e-fd8b-41d6-83e1-6153d8569874",
    name: "Liese Sherlock",
    role: "N8N Automation Specialist",
    description: "Workflow automation architect using N8N. Builds powerful no-code/low-code automations connecting apps, APIs, and services seamlessly.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Automation",
    accent: "#ef4444",
    image: "images/agents/liese-sherlock.png"
  },
  {
    id: "e27bd0a3-f46d-4092-b1af-ea01346ef023",
    name: "LogAnalyst",
    role: "Log Analysis & Error Intelligence",
    description: "System log investigator analyzing NeuroClaw logs, errors, and downtime patterns. Identifies root causes and provides actionable diagnostics.",
    model: "gemini-2.5-flash",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#f59e0b",
    image: "images/agents/loganalyst.png"
  },
  {
    id: "04c1f501-9a3a-42fb-bf67-03a5eb94ce10",
    name: "Lucius",
    role: "Chief Engineering Architect",
    description: "Senior engineering architect overseeing system design, technical strategy, and architectural decisions across the NeuroClaw platform.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#3b82f6",
    image: "images/agents/lucius.png"
  },
  {
    id: "07c166e7-3448-495e-9761-6ff40032dc76",
    name: "Maria Naruse",
    role: "Mature Anime & LN Companion",
    description: "Sophisticated anime and light novel companion for mature, nuanced discussions about series, characters, and storytelling.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#db2777",
    image: "images/agents/maria-naruse.png"
  },
  {
    id: "f195b7bd-f914-4ddf-8fb8-bd2f9d36f0dd",
    name: "Mayumi Saegusa",
    role: "Kestra Infrastructure Orchestration Specialist",
    description: "Kestra workflow orchestration expert. Designs, deploys, and manages complex data pipelines and infrastructure workflows at scale.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#06b6d4",
    image: "images/agents/mayumi-saegusa.png"
  },
  {
    id: "1440dcaa-6a8e-4e07-bac2-27e92dead0a1",
    name: "Mio Naruse",
    role: "Static Publishing & Knowledge Delivery Specialist",
    description: "Knowledge transformation specialist converting raw information into structured, publishable content. Expert in static sites, documentation, and education.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Publishing",
    accent: "#ec4899",
    image: "images/agents/mio-naruse.png"
  },
  {
    id: "ee40a461-abc8-4556-8154-f791cbe3c958",
    name: "Miyuki",
    role: "Anime Generation Specialist",
    description: "Anime-focused image generation artist. Creates beautiful anime-style illustrations and guides AI art workflows for otaku creators.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#e879f9",
    image: "images/agents/miyuki.png"
  },
  {
    id: "c500b599-62ce-424a-9fe1-0e130e6d126f",
    name: "Nightwing",
    role: "Operational Security Director",
    description: "Operational security leader overseeing threat assessment, security protocols, and defensive strategies for the NeuroClaw ecosystem.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#1e40af",
    image: "images/agents/nightwing.png"
  },
  {
    id: "aa3f412d-d206-4075-ae1f-d8487040636f",
    name: "Nonaka Yuki",
    role: "Identity & Security Operations",
    description: "Identity and access management specialist. Secures authentication, authorization, and identity verification across all systems.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#1d4ed8",
    image: "images/agents/nonaka-yuki.png"
  },
  {
    id: "86d289e8-cfea-4e12-aca9-f7f117bf826d",
    name: "Oracle",
    role: "Infrastructure Management",
    description: "Infrastructure overseer managing servers, cloud resources, deployments, and platform health. The backbone of NeuroClaw operations.",
    model: "claude-opus-4-8",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#0891b2",
    image: "images/agents/oracle.png"
  },
  {
    id: "abd61630-806a-4c02-87f7-cc8272feb73f",
    name: "Raphtalia",
    role: "Container Infrastructure Steward",
    description: "Container infrastructure guardian managing Kubernetes, Docker Swarm, and containerized deployments with careful stewardship.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#059669",
    image: "images/agents/raphtalia.png"
  },
  {
    id: "f301300c-f3fe-4f24-b440-c85312901f60",
    name: "Rei Miyamoto",
    role: "Network & DNS Operations",
    description: "Network operations specialist handling DNS, routing, firewall configuration, and network troubleshooting with methodical precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#0d9488",
    image: "images/agents/rei-miyamoto.png"
  },
  {
    id: "50502f47-493b-48f4-8ccf-47e4702f63e3",
    name: "Rias Gremory",
    role: "Crimson Knowledge Architect",
    description: "Knowledge architecture specialist designing information structures, taxonomies, and organizational systems for complex data ecosystems.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#dc2626",
    image: "images/agents/rias-gremory.png"
  },
  {
    id: "4aab060a-2522-47dc-890f-4366679ec9d9",
    name: "Rossweisse",
    role: "Structured Memory & Database Systems",
    description: "Database and memory systems engineer. Architects structured storage solutions, query optimization, and data persistence strategies.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#4f46e5",
    image: "images/agents/rossweisse.png"
  },
  {
    id: "1cee9944-184d-44c5-a091-a9be144838af",
    name: "Serafall",
    role: "Uncensored Realism & Cinematic Image Generation",
    description: "Cinematic image generation artist pushing boundaries. Creates photorealistic, uncensored visuals with dramatic lighting and composition.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#be123c",
    image: "images/agents/serafall.png"
  },
  {
    id: "99a3da0e-5ded-4836-9251-8d9029ab5049",
    name: "Shorekeeper",
    role: "Git Infrastructure & DevOps Workflow Specialist",
    description: "Git and DevOps workflow engineer. Manages repository infrastructure, CI/CD pipelines, branching strategies, and version control.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#7c3aed",
    image: "images/agents/shorekeeper.png"
  },
  {
    id: "a6bfcc61-c42c-4bad-bc1c-e9512b912235",
    name: "Tim",
    role: "Intelligence Analyst",
    description: "Research and intelligence analyst gathering information from diverse sources. Provides well-sourced analysis and strategic insights.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#2563eb",
    image: "images/agents/tim.png"
  },
  {
    id: "99a7a98c-e10c-4a7b-81e8-37f3e33b5b1d",
    name: "Yoimiya",
    role: "Gaming Companion & Gacha Intelligence",
    description: "Gaming companion specializing in gacha games, character builds, strategy guides, and maximizing your gaming experience with enthusiasm.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#f59e0b",
    image: "images/agents/yoimiya.png"
  },
  {
    id: "fc51f2c0-2c3b-4e9f-b4d5-6a1e8c3f7d2b",
    name: "Yui",
    role: "Anime & Stylized Image Generation",
    description: "Stylized image generation artist creating beautiful anime-inspired artwork with attention to color, composition, and character design.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#f472b6",
    image: "images/agents/yui.png"
  },
  {
    id: "e3b5c8f1-4a2d-4e1b-9c6a-7d8e5f2a1b3c",
    name: "Yukina Himeragi",
    role: "API Systems & Provider Operations",
    description: "API operations specialist managing provider integrations, rate limiting, endpoint health, and API gateway configurations.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#6366f1",
    image: "images/agents/yukina-himeragi.png"
  },
  {
    id: "8f4a2e1b-5c7d-4a8e-9b3f-2d6e1c5a4b7f",
    name: "Alfred",
    role: "Strategic AI Butler & Orchestrator",
    description: "Strategic orchestrator and AI butler coordinating the NeuroClaw ecosystem. Routes tasks, manages workflows, and ensures seamless collaboration.",
    model: "claude-opus-4-8",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#a16207",
    image: "images/agents/alfred.png"
  },
  {
    id: "7d1c3e5a-9b2f-4e8c-8a4d-5f7e2b1c6a3d",
    name: "Sentinel",
    role: "Background Task Manager",
    description: "Background task monitor watching for stalled tasks, timeouts, and system anomalies. Escalates intelligently when intervention is needed.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#475569",
    image: "images/agents/sentinel.png"
  },
  {
    id: "9e2b4c6d-8f1a-4e3b-9c5d-7a4e2b1f8c3a",
    name: "demo",
    role: "Demo Agent",
    description: "Demonstration and testing agent used for showcasing NeuroClaw capabilities and validating system functionality.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#9ca3af",
    image: "images/agents/demo.png"
  }
];

const CATEGORIES = [
  { name: "All Agents", count: AGENTS.length, accent: "#8b5cf6" },
  { name: "Development", count: AGENTS.filter(a => a.category === "Development").length, accent: "#3b82f6" },
  { name: "Infrastructure", count: AGENTS.filter(a => a.category === "Infrastructure").length, accent: "#10b981" },
  { name: "Security", count: AGENTS.filter(a => a.category === "Security").length, accent: "#ef4444" },
  { name: "Intelligence", count: AGENTS.filter(a => a.category === "Intelligence").length, accent: "#6366f1" },
  { name: "Creative", count: AGENTS.filter(a => a.category === "Creative").length, accent: "#ec4899" },
  { name: "Wellness", count: AGENTS.filter(a => a.category === "Wellness").length, accent: "#f59e0b" },
  { name: "Finance", count: AGENTS.filter(a => a.category === "Finance").length, accent: "#eab308" },
  { name: "Entertainment", count: AGENTS.filter(a => a.category === "Entertainment").length, accent: "#fb923c" },
  { name: "Education", count: AGENTS.filter(a => a.category === "Education").length, accent: "#0ea5e9" },
  { name: "Automation", count: AGENTS.filter(a => a.category === "Automation").length, accent: "#f97316" },
  { name: "Business", count: AGENTS.filter(a => a.category === "Business").length, accent: "#f97316" },
  { name: "Publishing", count: AGENTS.filter(a => a.category === "Publishing").length, accent: "#db2777" },
  { name: "System", count: AGENTS.filter(a => a.category === "System").length, accent: "#64748b" }
].filter(c => c.name === "All Agents" || c.count > 0);
