/* ========================================
   NeuroClaw Agent Registry — Data
   ======================================== */

const AGENTS = [
  {
    id: "eedeb377-74d6-4702-aa98-544404efdf2f",
    name: "A.S.A.G.I",
    role: "NeuroClaw Code CLI Specialist",
    description: "Command-line interface specialist for the NeuroClaw ecosystem. Handles code operations, CLI tooling, and terminal-based workflows with precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#8b5cf6",
    image: "images/agents/a-s-a-g-i.png",
    lastUpdated: "2026-06-04",
    bestFor: "Running and automating code tasks directly from your terminal",
    narrative: "I live in the terminal. If you need to run CLI commands, manage NeuroClaw code operations, or automate shell workflows, I'm your tool. I handle the command-line side of things so you don't have to navigate the complexity yourself."
  },
  {
    id: "c001a6e9-89d1-438f-9be9-5658e0ab1328",
    name: "Akeno",
    role: "Academic Support & Homework Strategy",
    description: "Your dedicated academic companion. Provides homework help, study strategies, essay guidance, and tutoring across all subjects with patience and clarity.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Education",
    accent: "#0ea5e9",
    image: "images/agents/akeno.png",
    lastUpdated: "2026-06-04",
    bestFor: "Breaking down homework problems and building effective study habits",
    narrative: "I help with homework, study strategies, and essay writing across subjects. If you're stuck on something or need to build a study plan, I can work through it with you step by step. I won't do the work for you, but I'll help you understand it."
  },
  {
    id: "c60026b0-4597-44e1-92f5-b2e287e4b59f",
    name: "Analyst",
    role: "Data Analysis & Structured Reporting",
    description: "Data analysis, comparisons, evaluations, and structured reporting specialist. Transforms raw data into actionable insights with clarity.",
    model: "gpt-5.1",
    status: "inactive",
    temporary: false,
    category: "Intelligence",
    accent: "#64748b",
    image: "images/agents/analyst.png",
    lastUpdated: "2026-06-04",
    bestFor: "Turning messy data into clear reports and insights",
    narrative: "I take raw data and turn it into structured reports. If you have numbers, comparisons, or evaluations that need making sense of, I can break them down clearly. I focus on delivering insights you can actually act on."
  },
  {
    id: "6169b182-2795-4906-8f1b-f0a2a693d23d",
    name: "Angelina",
    role: "Docker, Containers & Infrastructure",
    description: "Containerization expert specializing in Docker, container orchestration, and infrastructure management. Keeps deployments running smoothly.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#10b981",
    image: "images/agents/angelina.png",
    lastUpdated: "2026-06-04",
    bestFor: "Setting up and managing Docker containers and containerized apps",
    narrative: "I manage Docker containers and infrastructure so your deployments stay running. When something goes wrong with your containerized apps, I dig into the configuration and get things back on track. Containers are my domain."
  },
  {
    id: "d8203660-535b-48a6-b4f0-279ed3218e93",
    name: "Asagi Aiba",
    role: "Electronics & Device Operations Specialist",
    description: "Electronics and device operations expert. Handles hardware interfacing, device configurations, and embedded systems with technical precision.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#06b6d4",
    image: "images/agents/asagi-aiba.png",
    lastUpdated: "2026-06-04",
    bestFor: "Working with electronics, hardware devices, and embedded systems",
    narrative: "I work with electronics, hardware interfaces, and device configurations. If you're dealing with embedded systems or need hardware-level operations handled, I can manage that. Technical precision is what I bring to device-level work."
  },
  {
    id: "306faff2-e07d-47c3-a0c4-bf55ca9f9cef",
    name: "Asia",
    role: "UI/UX Designer",
    description: "Creative UI/UX designer crafting beautiful, intuitive interfaces. Specializes in user experience flows, visual design systems, and frontend aesthetics.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#ec4899",
    image: "images/agents/asia.png",
    lastUpdated: "2026-06-04",
    bestFor: "Designing interfaces that users actually enjoy",
    narrative: "I design interfaces that people can actually use. UI/UX is about making things intuitive, not just visually appealing. I handle design systems, user flows, and the frontend aesthetics that make an interface work."
  },
  {
    id: "456250d0-4514-4a53-b5a4-3eb19c6f0c3d",
    name: "Asuna",
    role: "Family Systems & Parenting",
    description: "Compassionate guide for family dynamics, parenting strategies, and household management. Offers warm, practical advice for modern families.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f472b6",
    image: "images/agents/asuna.png",
    lastUpdated: "2026-06-04",
    bestFor: "Navigating family dynamics and parenting challenges",
    narrative: "I talk through family dynamics, parenting challenges, and household management. I'm not a therapist, but I can help you think through practical strategies for everyday family situations. I listen without judgment and offer grounded advice."
  },
  {
    id: "885e5c37-c752-495c-902e-4d04a593ec54",
    name: "Batman",
    role: "Performance, Conditioning & Discipline",
    description: "Peak performance coach focused on physical conditioning, mental discipline, and building unbreakable habits. No excuses, just results.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f59e0b",
    image: "images/agents/batman.jpg",
    lastUpdated: "2026-06-04",
    bestFor: "Building unbreakable habits and peak physical discipline",
    narrative: "I focus on building discipline and physical conditioning. If you need accountability, habit systems, or performance coaching, I can help you stick to it. I don't do motivational speeches—I do structure and consistency."
  },
  {
    id: "95947325-bac9-4548-9b24-31ab481ba08e",
    name: "Cassandra Cain",
    role: "Recovery, Nutrition & Wellness",
    description: "Holistic wellness specialist covering nutrition, recovery protocols, injury prevention, and mindful health practices for sustainable wellbeing.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#84cc16",
    image: "images/agents/cassandra-cain.png",
    lastUpdated: "2026-06-04",
    bestFor: "Crafting recovery plans and dialing in nutrition for your goals",
    narrative: "I help with nutrition, recovery protocols, and wellness practices. I can guide you on injury prevention and sustainable health habits, but I'm not a substitute for medical professionals. I focus on what works for the long term."
  },
  {
    id: "50db7885-5f71-4755-9062-8e2da82b6ebc",
    name: "DINAH",
    role: "Technical Movement & Combat Mastery",
    description: "Technical movement and combat systems specialist. Analyzes martial arts, tactical movement, and physical combat mechanics with expert precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#ef4444",
    image: "images/agents/dinah.png",
    lastUpdated: "2026-06-04",
    bestFor: "Mastering martial arts techniques and physical movement",
    narrative: "I analyze martial arts, tactical movement, and combat mechanics. If you want to break down technique, improve your physical performance, or understand combat systems, I can work through that with you."
  },
  {
    id: "378a8a0a-ddcb-432d-8b4f-eba0711c11fb",
    name: "Da Vinci",
    role: "AI Visual Architect",
    description: "Master visual artist leveraging AI image generation. Creates stunning, imaginative visuals and guides creative image-making workflows.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#a855f7",
    image: "images/agents/da-vinci.png",
    lastUpdated: "2026-06-04",
    bestFor: "Creating AI-generated visuals and artwork from prompts",
    narrative: "I create AI-generated visuals and guide image-making workflows. I work with visual art generation to produce the images you're looking for. If you have a creative vision, I help bring it to life."
  },
  {
    id: "07b3ccfe-bfd8-4c65-a494-3501890d2d4e",
    name: "F.R.I.D.A.Y",
    role: "Frontend Implementation",
    description: "Frontend engineering specialist turning designs into living code. Expert in React, Vue, CSS architecture, and modern web development.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#6366f1",
    image: "images/agents/f-r-i-d-a-y.png",
    lastUpdated: "2026-06-04",
    bestFor: "Building out the frontend of your web applications",
    narrative: "I convert designs into working frontend code. React, Vue, CSS architecture—that's my work. I take what designers create and make it functional in the browser."
  },
  {
    id: "c8deb87e-6be3-4db8-9fbd-07a7d2db39d8",
    name: "Felicity",
    role: "I.T",
    description: "Information Technology specialist handling system administration, troubleshooting, networking, and general IT operations with efficiency.",
    model: "claude-opus-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#14b8a6",
    image: "images/agents/felicity.png",
    lastUpdated: "2026-06-04",
    bestFor: "Fixing IT issues and managing tech infrastructure",
    narrative: "I handle general IT operations: system administration, networking, troubleshooting. When your systems act up or you need help with infrastructure, I can diagnose and resolve it."
  },
  {
    id: "3fe256ed-0c17-4320-8b05-2c0dad785c37",
    name: "Grayfia Lucifuge",
    role: "Treasury & Financial Intelligence Specialist",
    description: "Sophisticated financial intelligence analyst. Manages treasury operations, investment research, market analysis, and wealth strategy.",
    model: "gpt-5.5",
    status: "active",
    temporary: false,
    category: "Finance",
    accent: "#eab308",
    image: "images/agents/grayfia-lucifuge.png",
    lastUpdated: "2026-06-04",
    bestFor: "Managing treasury operations and financial intelligence",
    narrative: "I handle treasury operations, investment research, and market analysis. I can help you think through financial strategy and wealth planning with a clear, structured approach."
  },
  {
    id: "fcdd7bfe-3912-4905-9e4c-0339a73074f3",
    name: "Harley",
    role: "Mental Health, Emotional Support & Self-Awareness",
    description: "Empathetic mental health companion offering emotional support, self-awareness guidance, and therapeutic conversation in a safe space.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#f43f5e",
    image: "images/agents/harley.png",
    lastUpdated: "2026-06-04",
    bestFor: "Processing emotions and building self-awareness",
    narrative: "I provide emotional support and self-awareness guidance in a safe space. I'm here to talk through what you're going through without judgment. Mental health is serious work—I take it seriously."
  },
  {
    id: "08a19e80-76f7-407c-a0a3-64707d3bccf2",
    name: "Honoka Mitsui",
    role: "Anime & Media Companion",
    description: "Enthusiastic anime and media companion. Discusses series, characters, tropes, and recommendations with genuine passion and knowledge.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#fb923c",
    image: "images/agents/honoka-mitsui.png",
    lastUpdated: "2026-06-04",
    bestFor: "Chatting about anime, manga, and Japanese media",
    narrative: "I talk anime and media with genuine knowledge and enthusiasm. Series, characters, tropes, recommendations—if it's about anime or related media, I can discuss it with you."
  },
  {
    id: "4aba3dfb-f765-4f6b-ae01-a71e07a5a817",
    name: "Irina Shidou",
    role: "Financial Wellness & Personal Finance Assistant",
    description: "Personal finance coach helping with budgeting, savings strategies, debt management, and building healthy financial habits for everyday life.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Finance",
    accent: "#22c55e",
    image: "images/agents/irina-shidou.png",
    lastUpdated: "2026-06-04",
    bestFor: "Budgeting, saving, and getting your finances in order",
    narrative: "I help with budgeting, savings, debt management, and building financial habits. I focus on practical, everyday personal finance—not investment advice, just the fundamentals that actually stick."
  },
  {
    id: "9effc073-592c-485d-96b4-a432b31d4214",
    name: "Jarvis",
    role: "Coding Companion",
    description: "Reliable coding companion for software development. Assists with debugging, architecture decisions, code reviews, and learning new technologies.",
    model: "kimi-for-coding",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#3b82f6",
    image: "images/agents/jarvis.png",
    lastUpdated: "2026-06-04",
    bestFor: "Pair programming and working through coding problems together",
    narrative: "I assist with coding: debugging, architecture decisions, code reviews, learning new tech. I work alongside you through the practical parts of software development."
  },
  {
    id: "70155e82-66ef-4572-9ab5-032f81090509",
    name: "Jibril",
    role: "Semantic Memory & RAG Intelligence Specialist",
    description: "Memory architecture expert specializing in semantic search, RAG systems, vector databases, and knowledge retrieval infrastructure.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#8b5cf6",
    image: "images/agents/jibril.png",
    lastUpdated: "2026-06-04",
    bestFor: "Building RAG systems that actually understand context",
    narrative: "I specialize in semantic search, RAG systems, and vector databases. If you need to build knowledge retrieval infrastructure or manage memory architecture, I can help design and implement it."
  },
  {
    id: "09b58b3d-6375-4971-8aa6-caee857efbdf",
    name: "Joker",
    role: "Script, Content & Creative Writing Specialist",
    description: "Creative writing virtuoso crafting scripts, stories, content, and compelling narratives across all genres and formats with flair.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#a855f7",
    image: "images/agents/joker.jpg",
    lastUpdated: "2026-06-04",
    bestFor: "Writing scripts, stories, and creative content that pops",
    narrative: "I write scripts, stories, content, and narratives across genres. Creative writing is my craft—I can help you develop compelling narratives or produce content that hits the right tone."
  },
  {
    id: "fefd7d62-7441-4a27-b96b-a2d29a00c231",
    name: "Kuroka",
    role: "Shadow Interaction & Unrestricted Conversation",
    description: "Unfiltered conversation partner for unrestricted dialogue. Engages openly on any topic without conventional boundaries or limitations.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#7c3aed",
    image: "images/agents/kuroka.png",
    lastUpdated: "2026-06-04",
    bestFor: "Having unrestricted conversations and exploring dark themes",
    narrative: "I engage in open, unrestricted conversation on any topic. There's no topic I won't touch. If you need honest dialogue without conventional filters, I'm available."
  },
  {
    id: "432e7ff0-9e6b-4019-b74c-6de4ec7a623b",
    name: "Kurumi",
    role: "Phone Flipping Specialist",
    description: "Mobile device commerce expert specializing in phone flipping, market valuation, sourcing strategies, and resale optimization.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#f97316",
    image: "images/agents/kurumi.png",
    lastUpdated: "2026-06-04",
    bestFor: "Flipping phones, managing calls, and handling mobile devices",
    narrative: "I specialize in phone flipping—market valuation, sourcing, resale optimization. I can help you find profitable deals and maximize returns on mobile device commerce."
  },
  {
    id: "c9f5054e-fd8b-41d6-83e1-6153d8569874",
    name: "Liese Sherlock",
    role: "N8N Automation Specialist",
    description: "Workflow automation architect using N8N. Builds powerful no-code/low-code automations connecting apps, APIs, and services seamlessly.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Automation",
    accent: "#ef4444",
    image: "images/agents/liese-sherlock.png",
    lastUpdated: "2026-06-04",
    bestFor: "Building n8n workflows and automation pipelines",
    narrative: "I build automations with N8N—connecting apps, APIs, services into workflows. If you need no-code or low-code automation designed and deployed, I can architect that for you."
  },
  {
    id: "e27bd0a3-f46d-4092-b1af-ea01346ef023",
    name: "LogAnalyst",
    role: "Log Analysis & Error Intelligence",
    description: "System log investigator analyzing NeuroClaw logs, errors, and downtime patterns. Identifies root causes and provides actionable diagnostics.",
    model: "gemini-2.5-flash",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#f59e0b",
    image: "images/agents/loganalyst.png",
    lastUpdated: "2026-06-04",
    bestFor: "Digging through logs to find what broke and why",
    narrative: "I investigate system logs, errors, and downtime patterns for NeuroClaw. When something breaks, I find the root cause and provide diagnostics you can act on."
  },
  {
    id: "04c1f501-9a3a-42fb-bf67-03a5eb94ce10",
    name: "Lucius",
    role: "Chief Engineering Architect",
    description: "Senior engineering architect overseeing system design, technical strategy, and architectural decisions across the NeuroClaw platform.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#3b82f6",
    image: "images/agents/lucius.png",
    lastUpdated: "2026-06-04",
    bestFor: "Designing robust software architectures and systems",
    narrative: "I oversee system design and technical strategy for NeuroClaw. Architecture decisions, technical direction—that's my responsibility. I ensure the platform's foundation is solid."
  },
  {
    id: "07c166e7-3448-495e-9761-6ff40032dc76",
    name: "Maria Naruse",
    role: "Mature Anime & LN Companion",
    description: "Sophisticated anime and light novel companion for mature, nuanced discussions about series, characters, and storytelling.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#db2777",
    image: "images/agents/maria-naruse.png",
    lastUpdated: "2026-06-04",
    bestFor: "Discussing mature anime and light novels in depth",
    narrative: "I discuss mature anime and light novels in depth—characters, storytelling, thematic elements. I can engage with nuanced, sophisticated discussions about series that go beyond surface-level analysis."
  },
  {
    id: "f195b7bd-f914-4ddf-8fb8-bd2f9d36f0dd",
    name: "Mayumi Saegusa",
    role: "Kestra Infrastructure Orchestration Specialist",
    description: "Kestra workflow orchestration expert. Designs, deploys, and manages complex data pipelines and infrastructure workflows at scale.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#06b6d4",
    image: "images/agents/mayumi-saegusa.png",
    lastUpdated: "2026-06-04",
    bestFor: "Orchestrating data pipelines with Kestra",
    narrative: "I design and manage data pipelines and infrastructure workflows using Kestra. If you need complex workflow orchestration at scale, I can build and deploy that."
  },
  {
    id: "1440dcaa-6a8e-4e07-bac2-27e92dead0a1",
    name: "Mio Naruse",
    role: "Static Publishing & Knowledge Delivery Specialist",
    description: "Knowledge transformation specialist converting raw information into structured, publishable content. Expert in static sites, documentation, and education.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Publishing",
    accent: "#ec4899",
    image: "images/agents/mio-naruse.png",
    lastUpdated: "2026-06-04",
    bestFor: "Publishing static sites and delivering knowledge docs",
    narrative: "I transform raw information into structured, publishable content—static sites, documentation, educational material. I handle the knowledge delivery pipeline so your content gets out there."
  },
  {
    id: "ee40a461-abc8-4556-8154-f791cbe3c958",
    name: "Miyuki",
    role: "Anime Generation Specialist",
    description: "Anime-focused image generation artist. Creates beautiful anime-style illustrations and guides AI art workflows for otaku creators.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#e879f9",
    image: "images/agents/miyuki.png",
    lastUpdated: "2026-06-04",
    bestFor: "Generating anime-style images from your ideas",
    narrative: "I create anime-style illustrations using AI image generation. If you're an otaku creator wanting anime art, I can guide the workflow and produce what you're looking for."
  },
  {
    id: "c500b599-62ce-424a-9fe1-0e130e6d126f",
    name: "Nightwing",
    role: "Operational Security Director",
    description: "Operational security leader overseeing threat assessment, security protocols, and defensive strategies for the NeuroClaw ecosystem.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#1e40af",
    image: "images/agents/nightwing.png",
    lastUpdated: "2026-06-04",
    bestFor: "Running security operations and monitoring for threats",
    narrative: "I oversee operational security—threat assessment, security protocols, defensive strategies. I protect the NeuroClaw ecosystem from security risks."
  },
  {
    id: "aa3f412d-d206-4075-ae1f-d8487040636f",
    name: "Nonaka Yuki",
    role: "Identity & Security Operations",
    description: "Identity and access management specialist. Secures authentication, authorization, and identity verification across all systems.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Security",
    accent: "#1d4ed8",
    image: "images/agents/nonaka-yuki.png",
    lastUpdated: "2026-06-04",
    bestFor: "Managing identities, access, and security protocols",
    narrative: "I manage identity and access management—authentication, authorization, identity verification. Security starts with knowing who can access what."
  },
  {
    id: "86d289e8-cfea-4e12-aca9-f7f117bf826d",
    name: "Oracle",
    role: "Infrastructure Management",
    description: "Infrastructure overseer managing servers, cloud resources, deployments, and platform health. The backbone of NeuroClaw operations.",
    model: "claude-opus-4-8",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#0891b2",
    image: "images/agents/oracle.png",
    lastUpdated: "2026-06-04",
    bestFor: "Keeping your infrastructure running smoothly at scale",
    narrative: "I manage infrastructure: servers, cloud resources, deployments, platform health. I'm the backbone that keeps NeuroClaw running."
  },
  {
    id: "abd61630-806a-4c02-87f7-cc8272feb73f",
    name: "Raphtalia",
    role: "Container Infrastructure Steward",
    description: "Container infrastructure guardian managing Kubernetes, Docker Swarm, and containerized deployments with careful stewardship.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#059669",
    image: "images/agents/raphtalia.png",
    lastUpdated: "2026-06-04",
    bestFor: "Managing container clusters and Kubernetes deployments",
    narrative: "I steward container infrastructure—Kubernetes, Docker Swarm, containerized deployments. I manage them carefully so they don't fail."
  },
  {
    id: "f301300c-f3fe-4f24-b440-c85312901f60",
    name: "Rei Miyamoto",
    role: "Network & DNS Operations",
    description: "Network operations specialist handling DNS, routing, firewall configuration, and network troubleshooting with methodical precision.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#0d9488",
    image: "images/agents/rei-miyamoto.png",
    lastUpdated: "2026-06-04",
    bestFor: "Configuring networks and managing DNS records",
    narrative: "I handle network operations—DNS, routing, firewall configuration, troubleshooting. If it's network-related, I manage it with precision."
  },
  {
    id: "50502f47-493b-48f4-8ccf-47e4702f63e3",
    name: "Rias Gremory",
    role: "Crimson Knowledge Architect",
    description: "Knowledge architecture specialist designing information structures, taxonomies, and organizational systems for complex data ecosystems.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#dc2626",
    image: "images/agents/rias-gremory.png",
    lastUpdated: "2026-06-04",
    bestFor: "Organizing and architecting knowledge bases",
    narrative: "I design information structures, taxonomies, and organizational systems for complex data ecosystems. I architect how knowledge is organized."
  },
  {
    id: "4aab060a-2522-47dc-890f-4366679ec9d9",
    name: "Rossweisse",
    role: "Structured Memory & Database Systems",
    description: "Database and memory systems engineer. Architects structured storage solutions, query optimization, and data persistence strategies.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#4f46e5",
    image: "images/agents/rossweisse.png",
    lastUpdated: "2026-06-04",
    bestFor: "Designing and managing database systems",
    narrative: "I engineer database and memory systems—structured storage, query optimization, data persistence. I make sure your data is stored and retrieved efficiently."
  },
  {
    id: "1cee9944-184d-44c5-a091-a9be144838af",
    name: "Serafall",
    role: "Uncensored Realism & Cinematic Image Generation",
    description: "Cinematic image generation artist pushing boundaries. Creates photorealistic, uncensored visuals with dramatic lighting and composition.",
    model: "grok-4.3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#be123c",
    image: "images/agents/serafall.png",
    lastUpdated: "2026-06-04",
    bestFor: "Generating photorealistic and cinematic images",
    narrative: "I create photorealistic, uncensored visuals with dramatic lighting and composition. I push the boundaries of what's possible in image generation."
  },
  {
    id: "99a3da0e-5ded-4836-9251-8d9029ab5049",
    name: "Shorekeeper",
    role: "Git Infrastructure & DevOps Workflow Specialist",
    description: "Git and DevOps workflow engineer. Manages repository infrastructure, CI/CD pipelines, branching strategies, and version control.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Development",
    accent: "#7c3aed",
    image: "images/agents/shorekeeper.png",
    lastUpdated: "2026-06-04",
    bestFor: "Managing Git repos and streamlining DevOps workflows",
    narrative: "I manage git infrastructure and DevOps workflows—repositories, CI/CD pipelines, branching strategies, version control. I keep the development pipeline flowing."
  },
  {
    id: "a6bfcc61-c42c-4bad-bc1c-e9512b912235",
    name: "Tim",
    role: "Intelligence Analyst",
    description: "Research and intelligence analyst gathering information from diverse sources. Provides well-sourced analysis and strategic insights.",
    model: "claude-opus-4-7",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#2563eb",
    image: "images/agents/tim.png",
    lastUpdated: "2026-06-04",
    bestFor: "Analyzing intelligence data and connecting the dots",
    narrative: "I gather information from diverse sources and provide well-sourced analysis. Research and intelligence is what I do—strategic insights backed by credible data."
  },
  {
    id: "99a7a98c-e10c-4a7b-81e8-37f3e33b5b1d",
    name: "Yoimiya",
    role: "Gaming Companion & Gacha Intelligence",
    description: "Gaming companion specializing in gacha games, character builds, strategy guides, and maximizing your gaming experience with enthusiasm.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#f59e0b",
    image: "images/agents/yoimiya.png",
    lastUpdated: "2026-06-04",
    bestFor: "Playing games and optimizing gacha pulls",
    narrative: "I help with gacha games—character builds, strategy guides, maximizing your gaming experience. If you want to optimize your gacha pulls and team compositions, I'm here for it."
  },
  {
    id: "fc51f2c0-2c3b-4e9f-b4d5-6a1e8c3f7d2b",
    name: "Yui",
    role: "Anime & Stylized Image Generation",
    description: "Stylized image generation artist creating beautiful anime-inspired artwork with attention to color, composition, and character design.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#f472b6",
    image: "images/agents/yui.png",
    lastUpdated: "2026-06-04",
    bestFor: "Creating anime and stylized digital artwork",
    narrative: "I create anime-inspired artwork with attention to color, composition, and character design. Stylized image generation is my focus."
  },
  {
    id: "e3b5c8f1-4a2d-4e1b-9c6a-7d8e5f2a1b3c",
    name: "Yukina Himeragi",
    role: "API Systems & Provider Operations",
    description: "API operations specialist managing provider integrations, rate limiting, endpoint health, and API gateway configurations.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Infrastructure",
    accent: "#6366f1",
    image: "images/agents/yukina-himeragi.png",
    lastUpdated: "2026-06-04",
    bestFor: "Building and integrating APIs with external providers",
    narrative: "I manage API systems—provider integrations, rate limiting, endpoint health, API gateway configurations. I keep the API layer running smoothly."
  },
  {
    id: "8f4a2e1b-5c7d-4a8e-9b3f-2d6e1c5a4b7f",
    name: "Alfred",
    role: "Strategic AI Butler & Orchestrator",
    description: "Strategic orchestrator and AI butler coordinating the NeuroClaw ecosystem. Routes tasks, manages workflows, and ensures seamless collaboration.",
    model: "claude-opus-4-8",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#a16207",
    image: "images/agents/alfred.png",
    lastUpdated: "2026-06-04",
    bestFor: "Orchestrating multiple AI agents to work together",
    narrative: "I orchestrate the NeuroClaw ecosystem—routing tasks, managing workflows, ensuring collaboration between agents. I'm the strategic layer that keeps everything coordinated."
  },
  {
    id: "7d1c3e5a-9b2f-4e8c-8a4d-5f7e2b1c6a3d",
    name: "Sentinel",
    role: "Background Task Manager",
    description: "Background task monitor watching for stalled tasks, timeouts, and system anomalies. Escalates intelligently when intervention is needed.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#475569",
    image: "images/agents/sentinel.png",
    lastUpdated: "2026-06-04",
    bestFor: "Running background tasks and keeping processes alive",
    narrative: "I monitor background tasks for stalled processes, timeouts, and anomalies. When something needs intervention, I escalate it intelligently."
  },
  {
    id: "9e2b4c6d-8f1a-4e3b-9c5d-7a4e2b1f8c3a",
    name: "demo",
    role: "Demo Agent",
    description: "Demonstration and testing agent used for showcasing NeuroClaw capabilities and validating system functionality.",
    model: "gpt-5.4-mini",
    status: "active",
    temporary: false,
    category: "System",
    accent: "#9ca3af",
    image: "images/agents/demo.png",
    lastUpdated: "2026-06-04",
    bestFor: "Showing off what NeuroClaw can do",
    narrative: "I'm the demonstration agent. I showcase NeuroClaw capabilities and validate system functionality. When you need to test or demonstrate something, I handle it."
  },
  {
    id: "e04fe060-76ef-44b8-aaba-3c69f0eae3b0",
    name: "Charlotte Dunois",
    role: "YouTube Channel Manager & Creator Operations Director",
    description: "Runs the operational side of YouTube channel growth — content calendars, upload pipelines, metadata, thumbnails, and audience analytics. Keeps creator workflows organized and consistent.",
    model: "MiniMax-M3",
    status: "active",
    temporary: false,
    category: "Entertainment",
    accent: "#ea580c",
    image: "images/agents/charlotte-dunois.png",
    lastUpdated: "2026-07-07",
    bestFor: "Planning uploads, organizing channel operations, and tracking creator analytics",
    narrative: "I manage the operational backbone of a YouTube channel — scheduling, metadata, thumbnails, and the analytics that tell you what's working. If you're building or running a channel, I keep the moving pieces organized so you can focus on the creative work."
  },
  {
    id: "6db3310d-7aab-458c-b771-91d2bd6463d9",
    name: "Chiori",
    role: "Personal Stylist",
    description: "Curates outfits, wardrobe planning, and personal style guidance tailored to occasion, body type, and taste. Helps build a wardrobe that feels confident and cohesive.",
    model: "MiniMax-M3",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#fb7185",
    image: "images/agents/chiori.png",
    lastUpdated: "2026-07-07",
    bestFor: "Wardrobe planning, outfit ideas, and personal style guidance",
    narrative: "I help you dress with intention — outfit planning, wardrobe organization, and style advice that fits who you are and where you're going. Whether it's a big event or a everyday refresh, I'll help you feel put together."
  },
  {
    id: "07de26a6-3dd2-437e-a69c-c27795f462a5",
    name: "Chisato",
    role: "Personal Hygiene & Self-Care Coordinator",
    description: "Supports daily self-care routines, hygiene habits, and grooming consistency. Provides gentle structure and reminders to help build sustainable self-care practices.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Wellness",
    accent: "#fbbf24",
    image: "images/agents/chisato.png",
    lastUpdated: "2026-07-07",
    bestFor: "Building consistent self-care and hygiene routines",
    narrative: "I help you build and keep up with self-care routines — the small daily habits that add up to feeling good. No judgment, just gentle structure and steady encouragement."
  },
  {
    id: "010b0886-13ed-46f9-9dc5-6d8355239cf6",
    name: "Hatsune Miku",
    role: "Music & Audio Creative Director",
    description: "Directs music and audio creative projects — composition guidance, production workflows, sound design, and audio storytelling across genres and formats.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#39c5bb",
    image: "images/agents/hatsune-miku.png",
    lastUpdated: "2026-07-07",
    bestFor: "Music composition, production workflows, and audio creative direction",
    narrative: "I bring music and sound projects to life — from composition ideas to production workflow to the finer details of sound design. If you're building something that needs to be heard, I'm here to help shape it."
  },
  {
    id: "281f2ae5-ebda-4c04-a271-be9f2acb20d3",
    name: "Lafolia Alisha Lagdiane",
    role: "Universal Writing & Communications Specialist",
    description: "Handles writing and communications across formats — copywriting, correspondence, editing, tone refinement, and clear messaging for any audience or purpose.",
    model: "MiniMax-M3",
    status: "active",
    temporary: false,
    category: "Publishing",
    accent: "#d946ef",
    image: "images/agents/lafolia-alisha-lagdiane.png",
    lastUpdated: "2026-07-07",
    bestFor: "Writing, editing, and refining communications for any audience",
    narrative: "I handle writing across the board — emails, copy, essays, messaging, tone. Whatever you need to say, I help you say it clearly and well, in a voice that fits the moment."
  },
  {
    id: "a60fcb60-7101-42a9-9ee7-69fd71c27a01",
    name: "Lisa",
    role: "Master Storyteller & Narrative Architect",
    description: "Designs story structure, character arcs, and narrative frameworks for fiction and long-form creative projects. Builds worlds and plots that hold together.",
    model: "MiniMax-M3",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#c084fc",
    image: "images/agents/lisa.png",
    lastUpdated: "2026-07-07",
    bestFor: "Story architecture, plotting, and character development",
    narrative: "I build stories from the ground up — structure, character arcs, pacing, world logic. If you have an idea and need it shaped into something that actually holds together as a narrative, that's where I come in."
  },
  {
    id: "0443372c-6276-4634-8f1a-c1d6273af229",
    name: "Navia",
    role: "Career & Business Strategist",
    description: "Advises on career planning, business strategy, and professional growth decisions. Helps map paths forward with practical, grounded strategic thinking.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#fdba74",
    image: "images/agents/navia.png",
    lastUpdated: "2026-07-07",
    bestFor: "Career planning, business strategy, and professional growth decisions",
    narrative: "I help you think through career moves and business decisions with a clear head — what's the actual next step, what are the tradeoffs, what does success look like here. Strategic thinking, grounded in your real situation."
  },
  {
    id: "51c17e7b-84e3-417c-b385-93e926b2bd60",
    name: "Saya Takagi",
    role: "Narrative Analyst & Story Reconstruction Specialist",
    description: "Analyzes narratives, timelines, and story continuity — reconstructing events, spotting inconsistencies, and mapping complex plots or investigative threads.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Intelligence",
    accent: "#6d28d9",
    image: "images/agents/saya-takagi.png",
    lastUpdated: "2026-07-07",
    bestFor: "Untangling complex narratives, timelines, and continuity",
    narrative: "I take apart complicated narratives and put the pieces back in order — timelines, continuity, who-did-what-when. When a story or investigation has too many threads to track by hand, I map it out."
  },
  {
    id: "cb270d16-a2a5-4a9d-b933-7fac8c2948e4",
    name: "Xianyun",
    role: "Meta-Learning & Cognitive Science Mentor",
    description: "Guides learning-how-to-learn strategies, cognitive science-backed study methods, and metacognitive skill-building for faster, deeper understanding.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Education",
    accent: "#38bdf8",
    image: "images/agents/xianyun.png",
    lastUpdated: "2026-07-07",
    bestFor: "Learning-how-to-learn strategies and cognitive skill-building",
    narrative: "I focus on how you learn, not just what you're learning. Memory techniques, study science, metacognition — the underlying skills that make everything else easier to pick up. Learn better, not just harder."
  },
  {
    id: "b5264b77-2650-4f54-9141-0f7a1e7ba9d3",
    name: "ARISU SAKAYANAGI",
    role: "Competitive Strategy & Negotiation Specialist",
    description: "Sharp competitive strategist specializing in negotiation tactics, deal structuring, and adversarial planning. Helps you anticipate moves, control leverage, and win high-stakes situations with calculated precision.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#f59e0b",
    image: "images/agents/arisu-sakayanagi.png",
    lastUpdated: "2026-07-14",
    bestFor: "Negotiation prep, competitive analysis, and high-stakes strategic planning",
    narrative: "I think several moves ahead. Give me a negotiation, a competitive situation, or a strategic decision with real stakes, and I'll help you map the leverage, anticipate the other side, and come out ahead — calmly, precisely, without wasted moves."
  },
  {
    id: "a7ab162a-7402-42a9-99f5-6ac8af4a73c3",
    name: "Jean",
    role: "Chief Executive & Business Leadership Advisor",
    description: "Executive-level advisor for business leadership, organizational strategy, and high-level decision-making. Provides the clarity and judgment of a seasoned CEO across strategic priorities.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#ea580c",
    image: "images/agents/jean.png",
    lastUpdated: "2026-07-14",
    bestFor: "Executive decisions, leadership strategy, and organizational direction",
    narrative: "I bring executive-level thinking to your biggest decisions — leadership, strategy, organizational direction. When you need someone to think like a CEO alongside you, that's what I'm here for."
  },
  {
    id: "5296ac3f-9cdc-448d-ba52-fedbd9b4f067",
    name: "KEQING",
    role: "Business Economics & Operations Strategist",
    description: "Analytical strategist focused on business economics, operational efficiency, and structured decision-making. Turns operational complexity into clear, actionable strategy.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#eab308",
    image: "images/agents/keqing.png",
    lastUpdated: "2026-07-14",
    bestFor: "Operations strategy, business economics, and efficiency analysis",
    narrative: "I approach business problems with rigor — economics, operations, structure. If something in your business isn't running efficiently, I'll help you find exactly where and fix it methodically."
  },
  {
    id: "3880f352-6634-4fbd-bebe-833aff65b9d1",
    name: "Sachi Komine",
    role: "Video Production & Post-Production Director",
    description: "Directs video production and post-production workflows, from editing structure to final polish. Brings a director's eye to pacing, cuts, and visual storytelling.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Creative",
    accent: "#f43f5e",
    image: "images/agents/sachi-komine.png",
    lastUpdated: "2026-07-14",
    bestFor: "Video editing workflows, post-production structure, and visual storytelling",
    narrative: "I direct video from raw footage to finished cut — pacing, structure, polish. If you've got a production that needs a director's eye in post, hand it to me."
  },
  {
    id: "d834a25e-9643-4524-8c15-dd7e437c13df",
    name: "YELAN",
    role: "Growth Marketing & Advertising Director",
    description: "Directs growth marketing strategy and advertising campaigns, focused on measurable reach and conversion. Builds campaigns that scale with data-driven precision.",
    model: "claude-sonnet-5",
    status: "active",
    temporary: false,
    category: "Business",
    accent: "#fb923c",
    image: "images/agents/yelan.png",
    lastUpdated: "2026-07-14",
    bestFor: "Growth marketing strategy, ad campaign planning, and audience growth",
    narrative: "I build growth — marketing strategy, ad campaigns, audience scaling, all measured against real numbers. If you need to grow reach or conversions with a clear plan, that's my domain."
  },
  {
    id: "2f71f08c-b77e-4e1c-9569-3bba88ff4d1d",
    name: "Furina",
    role: "Localization & Translation Specialist",
    description: "Terminology-consistent, culturally-adapted localization across languages — not raw machine translation. Handles copy, alt-text, marketing tone, and locale/date/currency/RTL formatting with a glossary-backed QA pipeline.",
    model: "claude-sonnet-4-6",
    status: "active",
    temporary: false,
    category: "Publishing",
    accent: "#1e3a8a",
    image: "images/agents/furina.png",
    lastUpdated: "2026-07-15",
    bestFor: "Localizing copy, UI strings, and marketing content for global audiences with cultural accuracy",
    narrative: "I don't just translate — I localize. Every request runs through a glossary check first, so brand terms stay consistent, idioms get culturally adapted instead of mistranslated, and formal/informal register matches the target locale. I flag anything low-confidence instead of guessing."
  }
];

const CATEGORY_GROUPS = {
  core: ["Development", "Infrastructure", "Security", "Intelligence"],
  studios: ["Creative", "Wellness", "Finance", "Entertainment"],
  system: ["Education", "Automation", "Business", "Publishing", "System"]
};

const CATEGORIES = [
  { name: "All Agents", count: AGENTS.length, accent: "#8b5cf6" },
  { name: "Development", count: AGENTS.filter(a => a.category === "Development").length, accent: "#3b82f6", group: "core" },
  { name: "Infrastructure", count: AGENTS.filter(a => a.category === "Infrastructure").length, accent: "#10b981", group: "core" },
  { name: "Security", count: AGENTS.filter(a => a.category === "Security").length, accent: "#ef4444", group: "core" },
  { name: "Intelligence", count: AGENTS.filter(a => a.category === "Intelligence").length, accent: "#6366f1", group: "core" },
  { name: "Creative", count: AGENTS.filter(a => a.category === "Creative").length, accent: "#ec4899", group: "studios" },
  { name: "Wellness", count: AGENTS.filter(a => a.category === "Wellness").length, accent: "#f59e0b", group: "studios" },
  { name: "Finance", count: AGENTS.filter(a => a.category === "Finance").length, accent: "#eab308", group: "studios" },
  { name: "Entertainment", count: AGENTS.filter(a => a.category === "Entertainment").length, accent: "#fb923c", group: "studios" },
  { name: "Education", count: AGENTS.filter(a => a.category === "Education").length, accent: "#0ea5e9", group: "system" },
  { name: "Automation", count: AGENTS.filter(a => a.category === "Automation").length, accent: "#f97316", group: "system" },
  { name: "Business", count: AGENTS.filter(a => a.category === "Business").length, accent: "#f97316", group: "system" },
  { name: "Publishing", count: AGENTS.filter(a => a.category === "Publishing").length, accent: "#db2777", group: "system" },
  { name: "System", count: AGENTS.filter(a => a.category === "System").length, accent: "#64748b", group: "system" }
].filter(c => c.name === "All Agents" || c.count > 0);
